# -*- coding: utf-8 -*-
"""EvenFibonacciNumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1weaVfVNi5YsoJoWrqugagl1gvLnRwCr3
"""

#Finding the sum of even values in the Fibonacci sequence whose values do not exceed four million

#Generating the Fibonacci sequence (start from 1)

F = [1,2] #Initial terms of Fibonacci sequence

while F[-1] < 4000000:
  s = F[-1] + F[-2] # "s" is the sum of previous two values in sequence
  F.append(s)

F.remove(F[-1])

#Finding the even-valued terms
even_values = [] 
for i in range (len(F)):
  if F[i] % 2 == 0:
    even_values.append(F[i])

#Result
print(sum(even_values))