# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQAliKpQEJHY5xkLNBjusWCn2bhVQPkK
"""

import numpy as np

n_list = list(np.arange(1,1000))

first_list = [] #Multiples of 3
second_list = [] #Multiples of 5

for i in range(len(n_list)):
  r1 = n_list[i] % 3
  if r1 == 0:
    first_list.append(n_list[i])
  r2 = n_list[i] % 5
  if r2 == 0:
    second_list.append(n_list[i])

#Deleting the duplicate values in two lists
for i in range(len(second_list)):
  if second_list[i] in first_list:
    first_list.remove(second_list[i])

for i in range(len(second_list)):
  if first_list[i] in second_list:
    second_list.remove(first_list[i])

#Result
print(sum(first_list) + sum(second_list))