# -*- coding: utf-8 -*-
"""SumSquareDiffeerence(Problem3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZbWREwcMVGP3rTF5V3sqAYVTXWVt27Dz
"""

#Finding the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum

#Genrating the list for the first one hundred natural numbers

import numpy as np
n = list(np.arange(1,101))

#Sum of the squares of the first 100 natural numbers

first_list = []
for i in range(len(n)):
  first_list.append(n[i]**2)

#The square of the sum of the first 100 natural numbers

s = sum(n)**2

#Result
print(s-sum(first_list))